build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related  APIs "
  contactDetails:
    name: "Silue Gninho - Developer"
    email: "dev225tech@gmail.com"
  onCallSupport:
    - (212) 012-3456
    - (212) 987-6543

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/
