build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related  QA APIs "
  contactDetails:
    name: "Dev22 Tech - QA Lead"
    email: "dev225tech@gmail.com"
  onCallSupport:
    - (212) 012-3456
    - (212) 987-6543

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/