
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: message-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: gninho/accounts
  tag: 3.3

containerPort: 8084

service:
  type: ClusterIP
  port: 8084
  targetPort: 8084

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: true
