
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: gninho/accounts
  tag: 3.3

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: false
kafka_enabled: true
